/**
 * Database Entity Types
 * These would normally be auto-generated by Prisma
 * For now, we define them manually for type safety
 */

export interface Organization {
  id: string;
  shop_domain: string;
  access_token: string; // encrypted
  scopes: string;
  is_active: boolean;
  plan: 'free' | 'basic' | 'pro' | 'enterprise';
  created_at: Date;
  updated_at: Date;
}

export interface User {
  id: string;
  organization_id: string;
  email: string;
  role: 'owner' | 'admin' | 'member';
  created_at: Date;
  updated_at: Date;
}

export interface Product {
  id: string;
  organization_id: string;
  shopify_product_id: string;
  title: string;
  description: string;
  vendor: string;
  product_type: string;
  handle: string;
  status: string;
  current_meta_title?: string;
  current_meta_description?: string;
  synced_at: Date;
  created_at: Date;
  updated_at: Date;
}

export interface ContentGeneration {
  id: string;
  organization_id: string;
  product_id: string;
  ai_model: string;
  meta_title: string;
  meta_description: string;
  schema_markup?: string;
  quality_score: number;
  status: 'draft' | 'approved' | 'published' | 'rejected';
  published_at?: Date;
  created_at: Date;
  updated_at: Date;
}

export interface ScheduledContent {
  id: string;
  organization_id: string;
  product_id: string;
  content_generation_id: string;
  scheduled_at: Date;
  status: 'scheduled' | 'processing' | 'completed' | 'failed' | 'cancelled';
  job_id?: string; // BullMQ job ID
  completed_at?: Date;
  error?: string;
  created_at: Date;
  updated_at: Date;
}

export interface BulkOperation {
  id: string;
  organization_id: string;
  operation_type: 'generate' | 'publish';
  total_items: number;
  processed_items: number;
  successful_items: number;
  failed_items: number;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'paused';
  job_id?: string; // BullMQ job ID
  started_at?: Date;
  completed_at?: Date;
  created_at: Date;
  updated_at: Date;
}

export interface WebhookLog {
  id: string;
  webhook_id: string; // Shopify webhook ID (for idempotency)
  organization_id: string;
  topic: string;
  shop_domain: string;
  payload: any; // JSON
  status: 'pending' | 'processed' | 'failed';
  processed_at?: Date;
  error?: string;
  retry_count: number;
  created_at: Date;
  updated_at: Date;
}

export interface AuditLog {
  id: string;
  organization_id: string;
  user_id?: string;
  action: string;
  entity_type: string;
  entity_id: string;
  changes?: any; // JSON
  ip_address?: string;
  user_agent?: string;
  created_at: Date;
}

// ============================================================================
// Q&A CONTENT ENGINE TYPES
// ============================================================================

export interface BusinessProfile {
  id: string;
  organization_id: string;
  business_name: string;
  industry: string; // 'ecommerce', 'saas', 'services', 'health', 'fashion', 'food'
  product_types: any; // JSON array
  target_audience: TargetAudience; // JSON
  brand_voice: BrandVoice; // JSON
  content_strategy: ContentStrategy; // JSON
  seo_strategy: SEOStrategy; // JSON
  product_strategy: ProductStrategy; // JSON
  advanced_settings: AdvancedSettings; // JSON
  created_at: Date;
  updated_at: Date;
}

export interface TargetAudience {
  demographics: string;
  expertiseLevel: 'beginner' | 'intermediate' | 'expert';
  painPoints: string[];
  searchBehavior: string;
}

export interface BrandVoice {
  tone: 'professional' | 'casual' | 'technical' | 'friendly' | 'authoritative' | 'conversational';
  personality: string[];
  avoidWords: string[];
  preferredWords: string[];
  exampleContent: string;
}

export interface ContentStrategy {
  primaryGoal: 'traffic' | 'conversions' | 'brand_awareness' | 'education';
  contentTypes: string[];
  postLength: 'short' | 'medium' | 'long';
  publishingFrequency: number;
  competitorUrls?: string[];
}

export interface SEOStrategy {
  targetKeywords: string[];
  avoidKeywords: string[];
  targetLocations: string[];
  languagePreference: 'en-US' | 'en-GB' | 'es' | 'fr' | 'de';
}

export interface ProductStrategy {
  productMentionFrequency: 'minimal' | 'moderate' | 'aggressive';
  ctaStyle: 'soft' | 'direct' | 'educational';
  preferredCTAs: string[];
}

export interface AdvancedSettings {
  factCheckingLevel: 'basic' | 'thorough' | 'expert';
  externalLinkingPolicy: 'minimal' | 'moderate' | 'generous';
  imageStyle: 'realistic' | 'illustrated' | 'minimal';
  schemaPreferences: string[];
}

export interface CustomQuestionTemplate {
  id: string;
  organization_id: string;
  business_profile_id: string;
  template: string;
  category?: string;
  priority: number;
  variables?: any; // JSON
  usage_count: number;
  created_at: Date;
}

export interface QAPage {
  id: string;
  organization_id: string;
  question: string;
  answer_content?: string;
  answer_markdown?: string;
  featured_image_url?: string;
  shopify_blog_id?: string;
  shopify_blog_post_id?: string;
  shopify_page_id?: string;
  shopify_url?: string;
  target_keyword?: string;
  meta_title?: string;
  meta_description?: string;
  h1?: string;
  schema_markup?: any; // JSON
  current_position?: number;
  best_position?: number;
  monthly_impressions: number;
  monthly_clicks: number;
  monthly_traffic: number;
  ctr?: number;
  seo_score?: number;
  status: 'draft' | 'pending_review' | 'published' | 'archived';
  published_at?: Date;
  last_optimized_at?: Date;
  created_at: Date;
  updated_at: Date;
}

export interface InternalLink {
  id: string;
  organization_id: string;
  source_page_type: string; // 'qa_page', 'product', 'collection'
  source_page_id?: string;
  source_url: string;
  target_page_type: string; // 'qa_page', 'product', 'collection'
  target_page_id?: string;
  target_url: string;
  anchor_text: string;
  context?: string;
  link_type: string; // 'contextual', 'cta', 'navigation'
  relevance_score?: number;
  created_at: Date;
}

export interface ContentPerformance {
  id: string;
  page_id: string;
  date: Date;
  impressions: number;
  clicks: number;
  ctr?: number;
  avg_position?: number;
  pageviews: number;
  unique_visitors: number;
  avg_time_on_page?: number;
  bounce_rate?: number;
  conversions: number;
  revenue?: number;
  created_at: Date;
}

export interface ABTest {
  id: string;
  organization_id: string;
  page_id?: string;
  element_type: string; // 'title', 'meta_description', 'h2s', 'cta', 'intro'
  control_value: string;
  variant_a_value?: string;
  variant_b_value?: string;
  traffic_split: any; // JSON
  results?: any; // JSON
  winner?: 'control' | 'variant_a' | 'variant_b';
  confidence?: number;
  status: 'running' | 'completed' | 'winner_applied' | 'cancelled';
  started_at: Date;
  ended_at?: Date;
  created_at: Date;
}

export interface AutomationRule {
  id: string;
  organization_id: string;
  rule_type: 'content_refresh' | 'auto_publish' | 'internal_linking' | 'ab_testing';
  configuration: any; // JSON
  enabled: boolean;
  last_executed_at?: Date;
  execution_count: number;
  created_at: Date;
  updated_at: Date;
}

export interface Competitor {
  id: string;
  organization_id: string;
  competitor_url: string;
  competitor_name?: string;
  content_topics?: any; // JSON
  keywords_they_rank_for?: any; // JSON
  content_gaps?: any; // JSON
  last_analyzed_at?: Date;
  created_at: Date;
}

// Prisma Client mock interface (would be auto-generated)
export interface PrismaClient {
  organization: any;
  user: any;
  product: any;
  contentGeneration: any;
  scheduledContent: any;
  bulkOperation: any;
  webhookLog: any;
  auditLog: any;
  businessProfile: any;
  customQuestionTemplate: any;
  qaPage: any;
  internalLink: any;
  contentPerformance: any;
  abTest: any;
  automationRule: any;
  competitor: any;
  $transaction: (queries: any[]) => Promise<any>;
  $disconnect: () => Promise<void>;
}
